### ISSUE TITLE
Flexrex + DOBS failing to attach/mount volumes

### ISSUE THREAD

**Issue by andrewsykim** [rexray/rexray#1185]
# Summary
When using kubernetes flexrex + dobs, the kubelet logs errors like: 
```
E0301 17:41:19.312166   11092 desired_state_of_world_populator.go:286] Failed to add volume "pod" (specName: "pod-0") for pod "ccb99726-1d75-11e8-bcf8-0401668d9803" to desiredStateOfWorld. err=failed to GetUniqueVolumeNameFromSpec for volumeSpec "pod-0" using volume plugin "flexvolume-rexray/flexrex" err=failed to GetVolumeName from volumePlugin for volumeSpec "pod-0" err=getvolumename command failed, status: Failure, reason: Could not get name of volume  via REX-Ray. Does it exist?
```

But the volume definitely exists and is sometimes already attached to the correct node. 

# Bug Reports
This section is for issues that relate to discovered problems or bugs.

## Version
Please paste the output of `rexray version`. For example:

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.0+1
OsArch: Linux-x86_64
Commit: 641297307121934b967eba0d6a1b380c3c543e69
Formed: Tue, 07 Nov 2017 15:55:48 UTC
```

## Expected Behavior
Volume is correctly attached/mounted to the pod plugin path. 

## Actual Behavior
Kubelet attempts to attach/mount the volume on the host using flexrex. Sometimes the voume gets attached but the volume is never mounted to the expected location
```
 ls -al /opt/kubelet/data/plugins/kubernetes.io/flexvolume/rexray/flexrex/mounts/
total 8
drwxr-x--- 2 root root 4096 Feb 15 03:45 .
drwxr-x--- 3 root root 4096 Jan 31 17:22 ..
```

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1) Create Kubernetes PV using flexrex driver
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  labels:
    app: my-app
  name: my-app-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: my-app-0
    namespace: default
  flexVolume:
    driver: rexray/flexrex
    fsType: ext4
    options:
      forceAttach: "true"
      forceAttachDelay: "60"
      volumeID: <REDACTED>
  persistentVolumeReclaimPolicy: Delete
status:
  phase: Bound
```
2) kubelet with pod assigned should has `--enable-controller-attach-detach=false` and flexrex script installed. rexray config is: 

## Configuration Files

```
$cat rexray.yml
libstorage:
  service: dobs
  integration:
    volume:
      operations:
        create:
          default:
            size: 30
dobs:
  token : <REDACTED>
  region: <REDACTED
```
