### ISSUE TITLE
Rexray start error - no IPs in the Data subnet Isilon

### ISSUE THREAD

**Issue by randrewedwards** [rexray/rexray#1225]
# Summary
I'm trying to start the rexray plugin but I'm receiving a weird API response back from the Isilion I'm trying to connect to.

## Version

```shell
rexray version
INFO[0000] updated log level                             logLevel=debug
DEBU[0000] os.args                                       time=1526549953887 val=[rexray version]
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.2
OsArch: Linux-x86_64
Commit: fc8bfbd2d02c2690fc3a755a9560dd12c88e0852
Formed: Sat, 24 Feb 2018 23:51:22 UTC
DEBU[0000] completed cli execution                       time=1526549953888
INFO[0000] exiting process                               time=1526549953888
DEBU[0000] completed onExit at end of program            time=1526549953888
```

## Expected Behavior
The rexray plugin starts and I can create volumes + exports

## Actual Behavior
Rexray plugin doesn't start

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1. 
```bash
rexray start
```
2. Error

## Configuration Files
Please paste any related configuration files, such as `/etc/rexray/config.yml`
in this section. Please use the appropriate formatting when pasting YAML.
content. For example:

```yaml
cat /etc/rexray/config.yml
rexray:
  logLevel: debug
libstorage:
  logging:
    level: debug
    httpRequests: true
    httpResponses: true
  # The libstorage.service property directs a libStorage client to direct its
  # requests to the given service by default. It is not used by the server.
  service: isilon
  server:
    services:
      isilon:
        driver: isilon
        isilon:
          endpoint: <endpoint>
          insecure: true
          username: <user>
          password: <pass>
          volumePath: /ifs/non-pci/non-prod/
          quotas: true
          nfshost: <host>
          dataSubnet: 10.32.192.0/23
```

Proper formatting of pasted content is very important as structured data can
sometimes be accidentally recorded incorrectly, affecting the desired outcome.

### Service Log
/var/log/rexray/rexray.log is empty

### Client Log
https://gist.github.com/randrewedwards/79e348101043895c045a04095b237cd5
This is the client log
