### ISSUE TITLE
[s3fs] Is it a right way to write docker-compose.yml like this?

### ISSUE THREAD

**Issue by darron1217** [rexray/rexray#1229]
I want to use s3fs plugin to connect my private storage `minio` but I can't fix syntax error (I'm dumb. Need help)

```yml
version: '3'

services:
   web:
     image: darron1217/docker-nginx-php-git:php7
     volumes:
       - web:/var/www/html
     ports:
       - 80:80

volumes:
    web:
      driver: rexray/s3fs
      driver_opts:
        accessKey: abcdef
        secretKey: 12345678
        endpoint: http://localhost:9001
        region: us-east-1
        disablePathStyle: false
        options:
        - url=http://localhost:9001
        - use_path_request_style
        - nonempty

```

The error
```
The Compose file '.\docker-compose.test.yml' is invalid because:
volumes.web.driver_opts.disablePathStyle contains an invalid type, it should be a string, or a number
volumes.web.driver_opts.options contains an invalid type, it should be a string, or a number
```

**Comment by darron1217** [comment]
No never mind

**Comment by Blaiserman** [comment]
What was the right syntax?

**Comment by cecchisandrone** [comment]
Please I have this error too, I need to specify nonempty option

**Comment by jaredvacanti** [comment]
Does anyone have a reference for how `rexray/s3fs` plugin would like options formatted in compose's `driver_opts`?

**Comment by codernew007** [comment]
maybe
```
version: '3.2'
volumes:
    s3:
        driver_opts:
                accessKey: minio
                secretKey: minio123
                endpoint: http://xxx:9000
                region: us-east-1
                disablePathStyle: 'false'
                options: "allow_other,use_path_request_style,nonempty,url=http://xxx:9000"
```
