### ISSUE TITLE
Does rexray supports distributed volumes?

### ISSUE THREAD

**Issue by holms** [rexray/rexray#1257]
I'm actually quite heavily tired to implement this beast so this is my last attempt to get some answer from non-active maintainers. 

Whatever I have volume.mount.preempt enabled or not I have the same outcome.
I can't launch 3 replicas on different host and mount rexray volume. I've got this message
 ```
VolumeDriver.Mount: docker-legacy: Mount: tools-npm-register: failed: resource not found
```
And rexray shows:

```
root@swarm-slave-1:~# rexray volume ls 
ID                                    Name                Status       Size
c845fcef-a5af-11e8-b36b-0242ac114508  tools-npm-register  unavailable  16
```
I'm using exactly same config as specified here: https://rexray.readthedocs.io/en/latest/user-guide/schedulers/docker/

```
libstorage:
  host: unix:///var/run/libstorage/localhost.sock
  integration:
    volume:
      mount:
        preempt: true
      create:
        default:
          size: 1 # GB
```

I can mount that volume only for single node. Yes I know there are flush problems, and that it's bad for consistency but i need to have mounted volume on **ALL HOSTS**, or else this software is useless in production using docker swarm. Whatever one of replicas will ask to detach one volume to use it for himself it doesn't matter for me, thing is if request  comes to one of the replicas it should be executed withing 20 seconds, files should be written/read from volume no matter what.
