### ISSUE TITLE
DOBS: Too many requests  status=500

### ISSUE THREAD

**Issue by holms** [rexray/rexray#1262]
# Summary

Seems to be there's rate limits withing digital ocean. 

# New Feature

I don't know if this solvable at all

# Bug Reports

FATA[0000] GET https://api.digitalocean.com/v2/volumes?per_page=200&region=ams3: 429 Too many requests  status=500

## Version
Please paste the output of `rexray version`. For example:

```shell
root@swarm-slave-1:~# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.3
OsArch: Linux-x86_64
Commit: 3afc7942dd8b1a88ed902344b4ece89374be87f7
Formed: Tue, 12 Jun 2018 15:45:51 UTC
```

## Expected Behavior

Working DOBS volumes

## Actual Behavior

Hit DO rate limits

## Steps To Reproduce
Re-deploying service maybe 10 times, and I think it's been failing, so it's been hopping from one swarm node to another, and here you go.

## Configuration Files
```yaml
# Ansible managed
rexray:
  logLevel: warn
libstorage:
  integration:
    volume:
      operations:
        mount:
          preempt: true
      create:
        default:
          size: 1
  service: dobs
  server:
    services:
      dobs:
        driver: dobs
dobs:
  token: xxx 
  region: ams3
  convertUnderscores: True
  statusInitialDelay: 100ms
  statusMaxAttempts: 10
  statusTimeout: 2m
```

## Logs
`rexray volume ls` gaved me this

```
FATA[0000] GET https://api.digitalocean.com/v2/volumes?per_page=200&region=ams3: 429 Too many requests  status=500
```
