### ISSUE TITLE
Error when starting  rexray with multiple modules configured

### ISSUE THREAD

**Issue by jimOnAir** [rexray/rexray#1269]
# Summary
I'm trying to use rexray with two modules: one for ebs and second with s3fs

# Bug Reports
When I trying to start rexray service I've got an error:
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                       
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x194490b]                                                                      
                                                                                                                                              
goroutine 334 [running]:                                                                                                                      
github.com/rexray/rexray/agent/csi/libstorage.(*driver).Serve(0xc4200eed00, 0x336c200, 0xc4203ced20, 0x7f55fd6dac50, 0xc42047c760, 0x2269200, 
0x336c200)                                                                                                                                    
        /go/src/github.com/rexray/rexray/agent/csi/libstorage/csi_service_libstorage.go:107 +0x4cb                                            
github.com/rexray/rexray/agent/csi.(*csiService).Serve(0xc4201ba690, 0x336c200, 0xc4203ced20, 0x0, 0x0, 0xc420142030, 0xc420387450)           
        /go/src/github.com/rexray/rexray/agent/csi/mod_csi_service.go:72 +0x65                                                                
github.com/rexray/rexray/agent/csi.(*mod).Start.func2.1(0xc42056e6e0, 0x33754a0, 0xc4203ced20)                                                
        /go/src/github.com/rexray/rexray/agent/csi/mod_csi.go:247 +0x8a                                                                       
created by github.com/rexray/rexray/agent/csi.(*mod).Start.func2                                                                              
        /go/src/github.com/rexray/rexray/agent/csi/mod_csi.go:246 +0x57
```

## Version
Please paste the output of `rexray version`. For example:

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.3+36
OsArch: Linux-x86_64
Commit: 8a6e866b9dfa50d5e73df8a3bfe44dcadf9ad1a2
Formed: Wed, 12 Sep 2018 16:07:05 UTC
```

## Configuration Files
Please paste any related configuration files, such as `/etc/rexray/config.yml`
in this section. Please use the appropriate formatting when pasting YAML.
content. For example:

```yaml
rexray:
rexray:
  logLevel: error
  modules:
    default-docker:
      type: docker
      desc: The default docker module
      host: unix:///run/docker/plugins/rexray.sock
      libstorage:
        service: ebs
    s3fs-docker:
      type: docker
      desc: s3fs docker module
      host: unix:///run/docker/plugins/s3fs-rexray.sock
      libstorage:
        service: s3fs
libstorage:
  service: ebs
  integration:
    volume:
      mount:
        preempt: false
      create:
        default:
          size: 1
  server:
    services:
      ebs:
        driver: ebs
      s3fs:
        driver: s3fs
ebs:
  accessKey: ACCESSKEY
  secretKey: SECRETKEY
  region: us-east-2
s3fs:
  accessKey: ACCESSKEY
  secretKey: SECRETKEY
  region: us-east-2
```
