### ISSUE TITLE
open /dev/vdc: no such file or directory

### ISSUE THREAD

**Issue by magnusja** [rexray/rexray#1274]
# Summary
Mounting of /dev/vdc fails, because disk is attached to /dev/vde (or similar).

# Bug Reports
This section is for issues that relate to discovered problems or bugs.

## Version
Please paste the output of `rexray version`. For example:

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.3
OsArch: Linux-x86_64
Commit: 3afc7942dd8b1a88ed902344b4ece89374be87f7
Formed: Tue, 12 Jun 2018 15:45:51 UTC
```

## Expected Behavior
Mounted volume.

## Actual Behavior
Error when starting docker container (mounting failed).

```
VolumeDriver.Mount: docker-legacy: Mount: app_services_redis_data: failed: open /dev/vdc: no such file or directory
```

It seems that the disks are getting confused. rexray is trying to mount a device which is not existing (e.g. /dev/vdc but correct would be /dev/vde). I have a very similar problem like described here: https://github.com/rexray/rexray/issues/477

Interesting is that in the Telekom Web Interface the volume is also identified as /dev/vdc but there is a warning that this might not be the actual identifier on the server.

![screenshot 2018-10-19 at 11 27 23](https://user-images.githubusercontent.com/1659457/47209983-035e5580-d392-11e8-9c81-506cc3a675e2.png)

## Steps To Reproduce

I am currently using Open Telekom Cloud with OpenStack/cinder. I configured rexray as a system service and I am using it within my docker swarm cluster.

## Configuration Files

```yaml
rexray:
  logLevel: debug
libstorage:
  logging:
    level:         debug
    httpRequests:  true
    httpResponses: true
  service: cinder
  server:
    services:
      cinder:
        driver: cinder
  integration:
    volume:
      operations:
        mount:
          preempt: false  # same problems when true

cinder:
  authURL: "{{ os_auth_url }}"
  userName: "{{ os_user_name}}"
  password: "{{ os_password }}"
  tenantName: "{{ os_tenant_name }}"
  regionName: "{{ os_region }}"
  domainName: "{{ os_domain_name }}"
```

### Service Log
https://gist.github.com/magnusja/3ecc3fd9a113d1b0769ee7a138f2b4c0
