### ISSUE TITLE
rexray s3fs + minio + raspberry pi + docker plugin. mount failed: no such file or directory

### ISSUE THREAD

**Issue by ngalayko** [rexray/rexray#1275]
# Summary
I am trying to set up persistent storage for Docker Swarm on Raspberry PI. I am using rexray to store data in a minio cluster (https://minio.io/). Minio completely implements s3 API. 
Since I didn't find an image for arm32v7 Docker plugin, I built my own. I suspect that the problem is in the Dockerfile, but not sure what is the problem. 

# Bug Reports

When a container is being created, I get an error when mounting a volume. 
Note that bucket in the registry is created, but no files are added.

## Version
I am not able to run the command, but I use binary `stable/0.11.3/rexray-Linux-ARMv7-0.11.3`

## Expected Behavior
Volumes are created without any problems. 

## Actual Behavior
Error when starting a container:
```
starting container failed: error while mounting volume '/var/lib/docker/plugins/a073a430966c9e2a4c94d5df03353e2d43a85b866aa81e3a03f8d4def7808a65/rootfs': VolumeDriver.Mount: docker-legacy: Mount: matomo-html: failed: open matomo-html: no such file or directory
```

## Steps To Reproduce

1. Setup docker swarm cluster on 4 raspberry pi 
2. Run minio cluster with https://github.com/ngalayko/server/blob/master/compose/arm32/docker-compose.storage.yaml
3. install docker plugin `docker plugin install ngalayko/rexray-s3fs`
4. run the file on docker swarm https://github.com/ngalayko/server/blob/master/compose/arm32/docker-compose.analytics.yaml

## Configuration Files

Dockerfile for a plugin I use:
```Dockerfile
FROM arm32v7/debian:7.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        wget 

RUN wget -q https://dl.bintray.com/rexray/rexray/stable/0.11.3/rexray-Linux-ARMv7-0.11.3.tar.gz -O rexray.tar.gz \
        && tar -xvzf rexray.tar.gz -C /usr/bin \
        && rm rexray.tar.gz

RUN mkdir -p /etc/rexray /run/docker/plugins /var/lib/rexray/volumes /var/lib/libstorage/volumes

ADD config.yaml /etc/rexray/config.yaml

ENTRYPOINT ["rexray", "-c", "/etc/rexray/config.yaml"]
```

This is the config file, it's embedded in the Docker plugin.
```yaml
rexray:
    loglevel: debug
libstorage:
    service: s3fs
    integration:
        volume:
            operations:
                create:
                    default:
                        fsType: ext4
                mount:
                    preempt: true
s3fs:
    accessKey: <key>
    secretKey: <key>
    endpoint: http://localhost:9000  
    region: us-east-1
    disablePathStyle: false 
    options:
    - url=http://localhost:9000
    - use_path_request_style
    - nonempty
```

This is the script I use to create a plugin (https://github.com/ngalayko/server/tree/master/plugins/rexray-plugin)
```
set -ex
plugin="$1"
TMPDIR=$(mktemp -d rexray.tmp.XXXXX)
image=$(docker build . -q)
docker create --name rexray "$image"
mkdir -p $TMPDIR/rootfs
docker export -o $TMPDIR/rexray.tar rexray
docker rm -vf rexray
( cd $TMPDIR/rootfs && tar xf ../rexray.tar )
cp config.json $TMPDIR
docker plugin rm "$plugin" || true
docker plugin create "$plugin" "$TMPDIR"
docker plugin push "$plugin" 
rm -rf "$TMPDIR"
```

## Docker daemon logs from `/var/log/daemon.log`

log file for 3 minutes from master node: https://gist.github.com/ngalayko/da388ac625d8ebdbfd6c89c8c085a53c

You can search for `Mount: matomo-html: failed: open matomo-html: no such file or directory`
Full cycle is repeated ~4 times in the log file
