### ISSUE TITLE
Volume attachment race condition

### ISSUE THREAD

**Issue by Trane9991** [rexray/rexray#1284]
# Summary
I'm using ECS with the RexRay EBS driver and staring ECS task with 3 container with it, and each of them should mount the volume. Problem is all of them starting relatively at the same time and trying to attach the same volume at the same time, one of the, succeds and the rest fails with the error `"error while mounting volume '': VolumeDriver.Mount: docker-legacy: Mount: ...: failed: volume already attached to a host",`

# Bug Reports
Multiple containers trying to mount the volume results in `"error while mounting volume '': VolumeDriver.Mount: docker-legacy: Mount: ...: failed: volume already attached to a host",`

## Version
`docker.io/rexray/ebs:latest`

## Expected Behavior
Volume successfuly mounted into all containers

## Actual Behavior
ECS task fail to start because volume can't be mounted

## Logs
```
Nov 28 10:49:23 ip-10-10-0-251.ec2.internal dockerd[3733]: time="2018-11-28T10:49:23Z" level=error msg="time=\"2018-11-28T10:49:23Z\" level=error msg=\"volume already attached to a host\" 
Nov 28 10:49:24 ip-10-10-0-251.ec2.internal dockerd[3733]: time="2018-11-28T10:49:24Z" level=error msg="time=\"2018-11-28T10:49:24Z\" level=error msg=\"error: api call failed\" 
Nov 28 10:49:24 ip-10-10-0-251.ec2.internal dockerd[3733]: time="2018-11-28T10:49:24Z" level=error msg="time=\"2018-11-28T10:49:24Z\" level=error msg=\"docker-legacy: Mount: failed: volume already attached to a host
```

**Comment by tomalok** [comment]
EBS doesn't support simultaneous mounting...  Try EFS and/or S3FS instead.

**Comment by remilapeyre** [comment]
Hi @tomalok, the issue here is not simultaneous mounting, we are having the same issue with an EBS that should be mounted on only one instance and have a workaround but there is indeed a bug here.

Here's how to reproduce the issue:

Create a Rexray EBS volume:  `sudo docker volume create --driver rexray/ebs --name rexray_test`

Start this `docker-compose.yml`:

```
version: '3.8'
services:
  nginx1:
    image: nginx
    volumes:
      - rexray_test:/data
  nginx2:
    image: nginx
    volumes:
      - rexray_test:/data

volumes:
  rexray_test:
    external:
      name: rexray_test
```

The EBS need to be attached to one instance but the race condition will try to attach it twice to this instance and will fail with the error message @Trane9991 gave.

This can currently be worked around using 

```
version: '3.8'
services:
  nginx1:
    image: nginx
    volumes:
      - rexray_test:/data
  nginx2:
    image: nginx
    volumes:
      - rexray_test:/data
    depends_on:
      - "nginx1"

volumes:
  rexray_test:
    external:
      name: rexray_test
```
