### ISSUE TITLE
FlexRex Kubernetes plugin causes mount conflicts between pods

### ISSUE THREAD

**Issue by guyklein24** [rexray/rexray#1287]
# Summary
Flexrex causing mount conflicts between pods that are scheduled on the same node and attached to volumes with the same prefix e.g:

**vol-data-2**
**vol-data-2**1

## Version
Please paste the output of `rexray version`. For example:

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.3
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: 3afc7942dd8b11a88ed902344b4ece89374e87f7
Formed: Tue, 12 Jun 2018 18:45:51 IDT
```
openshift v3.9.31
kubernetes v1.9.1+a0ce1bc657

## Expected Behavior
Pod's should mount the exact volume that defined in their PV's yaml

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1. Install [Flexrex kubernetes plugin](https://rexray.readthedocs.io/en/stable/user-guide/schedulers/kubernetes/).
 
2. Create 2 Volumes with the same prefix

```shell
$ rexray volume create vol-data-2
$ rexray volume create vol-data-21

```
3. Create 2 pods with *FlexREX* persistent volumes:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: pod-2
    volumeMounts:
    - mountPath: /test-pd
      name: rexvol
  volumes:
  - name: rexvol-2
    flexVolume:
      driver: rexray/flexrex
      fsType: xfs
      options:
        volumeID: vol-data-2
        forceAttach: "true"
        forceAttachDelay: "15"
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-21
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: pod-21
    volumeMounts:
    - mountPath: /test-pd
      name: rexvol-21
  volumes:
  - name: rexvol-0
    flexVolume:
      driver: rexray/flexrex
      fsType: xfs
      options:
        volumeID: rexvol-21
        forceAttach: "true"
        forceAttachDelay: "15"
```

**Make sure that the pods are scheduled on the same node. you can use** ```nodeSelector```

I think what causing the issue is the rexray cli tool:
```shell
rexray volume ls vol-data-2
```
returns all the volumes with **vol-data-2** prefix:
```shel 
ID                Name         Status     Size
d12db8300000048    vol-data-2   attached   8
d12db8300000049    vol-data-21  attached   8
```

The Flexrex Kubernetes plugin script uses this command within the mount process.
see (https://github.com/rexray/rexray/blob/master/scripts/scripts/flexrex):
```rexray volume ls vol-data-2 --format json --path | jq -r '.[0].attachments[0].deviceName```
 returns other value in each time randolmly.

As a result, there is an option that both pods will mount the same device:

4. Run ```df -h``` on pod-2:
```shell
Filesystem     Size  Used  Avail  Use%  Mounted on
/dev/scinib    8G    16K    8G     1%      /test-pd
```
5. Run ```df -h``` on pod-21:
```shell
Filesystem     Size  Used  Avail  Use%  Mounted on
/dev/scinib    8G    16K    8G     1%      /test-pd
```
As you can see, both pods mounted the same volume.
