### ISSUE TITLE
 0.11.4 args=[ceph-conf --lookup mon_host] error

### ISSUE THREAD

**Issue by f1-outsourcing** [rexray/rexray#1297]
I just installed the rexray rpms, created the config.yml and get this error. (Ceph is configured correctly, because I can created the block device with rbdmap map)

Can this be because of a syntax error, I had "mon host = x.x.x.x,x.x.x.x,x.x.x.x", I changed it to "mon_host = x.x.x.x,x.x.x.x,x.x.x.x". But that gives same error. Maybe I can put the monitors in the config??

```
[@m03 ceph]# rexray volume ls
ERRO[0001] Error running command                         args=[ceph-conf --lookup mon_host] error=exit status 1 host=unix:///var/run/rexray/383072738.sock server=peach-razor-md service=rbd stderr= storageDriver=libstorage time=1549822647896 txCR=1549822647 txID=311d12cb-580e-4139-5c79-cb0f7cec5acc
Oops, an error occured!
```

```
[@m03 rexray]# cat config.yml
libstorage:
  # The libstorage.service property directs a libStorage client to direct its
  # requests to the given service by default. It is not used by the server.
  service: rbd
  server:
    services:
      rbd:
        driver: rbd
        rbd:
          defaultPool: rbd
          cephArgs: --id rbd.mesos
```

rexray-controller-0.11.4-1.x86_64
rexray-0.11.4-1.x86_64
rexray-client-0.11.4-1.x86_64
rexray-agent-0.11.4-1.x86_64
CentOS Linux release 7.6.1810 (Core)
