### ISSUE TITLE
rexray not releasing volume

### ISSUE THREAD

**Issue by f1-outsourcing** [rexray/rexray#1301]
I configured postgres to run in marathon and it was looping through deployment, I guess because the volume was unavailable. After I manually executed "rexray volume unmount app-postgres" the app deployed.
Should this configuration not release mounts on other hosts?

```
[@m02 ~]# cat /etc/rexray/config.yml
rexray:
  logLevel: warn
  storageDrivers:
  - rbd
  volume:
   mount:
     preempt: true
   unmount:
     ignoreusedcount: true
   remove:
     disable: true
libstorage:
  service: rbd
rbd:
  defaultPool: app
  cephArgs: --id app.mesos --cluster ceph

[@m02 ~]# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.4
OsArch: Linux-x86_64
Commit: e7414eaa971b27977d2283f2882825393493179d
Formed: Tue, 15 Jan 2019 17:03:57 CET
```
