### ISSUE TITLE
Fill `volume.Mountpoint` field

### ISSUE THREAD

**Issue by kumy** [rexray/rexray#1305]
# Summary
The volume `Mountpoint` is not present when using `docker volume inspect <some_volume>`. This is related to https://github.com/camptocamp/bivac/issues/256

## Version
```shell
$ rexray version

REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.4
OsArch: Linux-x86_64
Commit: e7414eaa971b27977d2283f2882825393493179d
Formed: Tue, 15 Jan 2019 17:03:57 CET
```

## Expected Behavior
I expect the command `docker volume inspect test` to display the path where the volume is mounted on host filesystem.
```json
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z",
        "Driver": "rexray",
        "Labels": null,
        "Mountpoint": "/var/lib/rexray/test",
        "Name": "test",
        "Options": null,
        "Scope": "global",
        "Status": {
            "availabilityZone": "nova",
            "fields": null,
            "iops": 0,
            "name": "test",
            "server": "cinder",
            "service": "cinder",
            "size": 1,
            "type": "classic"
        }
    }
]
```

## Actual Behavior
The `Mountpoint` field is empty.
```json
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z",
        "Driver": "rexray",
        "Labels": null,
        "Mountpoint": "",
        "Name": "test",
        "Options": null,
        "Scope": "global",
        "Status": {
            "availabilityZone": "nova",
            "fields": null,
            "iops": 0,
            "name": "test",
            "server": "cinder",
            "service": "cinder",
            "size": 1,
            "type": "classic"
        }
    }
]
```

## Steps To Reproduce
* Create a volume: `rexray volume create --size 1 test`
* Mount the volume on host: `rexray volume mount test`
* Inspect the volume using `docker`: `docker volume inspect test`

## Configuration Files
```yaml
rexray:
  logLevel: debug
libstorage:
  logging:
    level: debug
    httpRequests: true
    httpResponses: true
  service: cinder
  integration:
    volume:
      operations:
        create:
          default:
            size: 1
cinder:
  domainName: Default
  authURL: https://auth.cloud.ovh.net/
  userName: xxx
  password: xxx
  regionName: xxx
  tenantID: xxx
  tenantName: xxx
```

### Service Log
https://gist.github.com/kumy/6d06aaac1992b5d475a9f24337bd0fc5

### Client Log
https://gist.github.com/kumy/93386e7e6f74527629b3f5a1dfc0a67d
