### ISSUE TITLE
Confusing output from `docker volume ls`

### ISSUE THREAD

**Issue by alanhughes** [rexray/rexray#1316]
# Summary
Output of `docker volume ls` is confusing. This is probably not a bug and is instead expected behaviour, but I just wanted some clarification on what I should expect to see.

I am running rexray on Mesosphere DC/OS in AWS using the EBS plugin.

## Version
Installed rexray using the docker plugin, so `rexray version` gives "command not found". 
From startup logs:
```
REX-Ray
-------
Binary: /opt/mesosphere/packages/rexray--adc7e1259778f2db5ed032a5844dc44f4b6993fe/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.2
OsArch: Linux-x86_64
Commit: fc8bfbd2d02c2690fc3a755a9560dd12c88e0852
```
Output of `docker plugin ls`:
```shell
# docker plugin ls
ID                  NAME                DESCRIPTION              ENABLED
70efa677824b        rexray/ebs:0.11.4   REX-Ray for Amazon EBS   true
```

## Expected Behavior
I would expect `docker volume ls` to show the single volume that has been created using rexray.

## Actual Behavior
`docker volume ls` output is as follows:
```
DRIVER              VOLUME NAME
rexray              <some-instance-name>
rexray/ebs:0.11.4   <some-instance-name>
...
...
```
displaying every single EBS volume that exists in the same AZ as the AWS instance.

## Steps To Reproduce
Simply run `docker volume ls`

## Configuration Files
`/etc/rexray/config.yml`

```yaml
  loglevel: info
  service: ebs
libstorage:
  integration:
    volume:
      operations:
        unmount:
          ignoreusedcount: true
  server:
    tasks:
      logTimeout: 5m
```
`/opt/mesosphere/etc/rexray.conf`
```yaml
rexray:
  loglevel: info
  service: ebs
libstorage:
  integration:
    volume:
      operations:
        unmount:
          ignoreusedcount: true
  server:
    tasks:
      logTimeout: 5m
```
