### ISSUE TITLE
Rex-ray docker plugin cannot autoprovision EBS using cloudformation with Scope: Task

### ISSUE THREAD

**Issue by ericchaves** [rexray/rexray#1317]
# Bug Reports
I'm using cloudformation to provision EBS volumes for ECS Tasks for large temp data (ie volume does not need to persist once container is removed). When I configure the volume with `Scope: shared` EBS are provisioned successfully. If I use `Scope: task` I got the error `task scoped volume could not be autoprovisioned`

## Version
REX-ray being installed as plugin (`docker plugin install rexray/ebs REXRAY_PREEMPT=true EBS_REGION=${AWS::Region} --grant-all-permissions`). Not sure how check the requested info since the service is not presented.

## Expected Behavior
Expected the volume to be autoprovisioned and mounted when a new container (ECS task) is launched. When the task is finished I expect the volume to be deleted.

## Actual Behavior
When a new container is launched I got the error `task scoped volume could not be autoprovisioned`.

The Cloudformation below contains the parameters used to configure the REX-Ray volume:

```
KuririnTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: kuririn
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      TaskRoleArn: !Ref ECSTaskRole
      Volumes:
      - Name: kuririn-data
        DockerVolumeConfiguration:
          Autoprovision: true
          Driver: rexray/ebs
          DriverOpts:
            size: 200
            ebstype: gp2
          Scope: task
```
