### ISSUE TITLE
docker rexray/dobs fails to find volume if name contains underscores

### ISSUE THREAD

**Issue by spditner** [rexray/rexray#1318]
# Summary

Creating a volume with an underscore succeeds, however it can not be mounted

## Version

```shell
REX-Ray
-------
Binary: /var/lib/docker/plugins/4dcf624b542367dd4b6ff0d4687526ec415c0ac0afc62da0a82f2c88c1bb3e22/rootfs/usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.4
OsArch: Linux-x86_64
Commit: e7414eaa971b27977d2283f2882825393493179d
Formed: Tue, 15 Jan 2019 16:03:57 UTC
```

## Expected Behavior

If it is possible to create a volume with underscores, it should be mountable, or otherwise throw an error

## Workaround

Do not use underscores in volume names

## Actual Behavior

A volume name containing an underscore is not mountable

## Steps To Reproduce

```
# docker volume create -d rexray/dobs --name data_1 --opt=size=1
# docker run -it --volume-driver=rexray/dobs -v data_1:/data busybox /bin/sh
docker: Error response from daemon: error while mounting volume '': VolumeDriver.Mount: docker-legacy: Mount: data_1: failed: problem with device discovery.
```

## Configuration Files

Default provided with rexray/dobs:

```
# cat /var/lib/docker/plugins/*/rootfs/etc/rexray/rexray.yml
rexray:
  loglevel: warn
libstorage:
  service: dobs
  integration:
    volume:
      operations:
        create:
          default:
            fsType: ext4
        mount:
          preempt: false
  server:
    services:
      dobs:
        driver: dobs
```

## Logs

No logs beyond the startup message when I dug through:

``` /var/lib/docker/plugins/*/rootfs/var/log/rexray/*.log```

Docker plugin does not provide additional logs
