### ISSUE TITLE
DOBS plugin - Error when using docker stack deploy

### ISSUE THREAD

**Issue by autoize** [rexray/rexray#1321]
# Summary
When using the rexray/dobs plugin to deploy a Docker stack, some services fail to start because there is an error mounting the DigitalOcean Block Volume. We have tried using both volume name with (let docker stack deploy it using the rexray/dobs driver) and without underscores (by creating them externally to the stack file), after referring to issue #1318. After bringing down the stack with ```docker stack rm stackname```, it's impossible to remove the volumes that failed to mount through an ordinary ```docker volume rm volumename``` except by deleting it through the DO dashboard. 

Even after doing a ```docker system prune``` and ensuring there are no containers (stopped or otherwise) left on the host, the volumes which failed to mount still cannot be removed.

Output of ```docker volume rm volume1 volume2 volume3```

```Error response from daemon: remove volume1: VolumeDriver.Remove: docker-legacy: Remove: volume1: failed: volume currently attached```
```Error response from daemon: remove volume2: VolumeDriver.Remove: docker-legacy: Remove: volume2: failed: volume currently attached```
```Error response from daemon: remove volume3: VolumeDriver.Remove: docker-legacy: Remove: volume3: failed: volume currently attached```

## Version

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.4
OsArch: Linux-x86_64
Commit: e7414eaa971b27977d2283f2882825393493179d
Formed: Tue, 15 Jan 2019 16:03:57 UTC
```

## Expected Behavior
The volumes mount correctly to the containers being started up for the Docker services. 

## Actual Behavior
* The volumes are created and can be viewed in DigitalOcean's dashboard, and they are also visible in ```docker volume ls```

* However, the services that rely on RexRay volumes never start, with Replicas 0/1. 

* Output of ```docker service ps stackname_mysql --no-trunc```

```femuf23upttkk53mhh229zfzb    \_ stackname_mysql.1   percona/percona-server:5.7@sha256:237243719c15ee0954a8e9d83882ef9aa6527beb9f8a9ec236e8a0fb45d86a87   docker1             Shutdown            Rejected 4 seconds ago    "VolumeDriver.Mount: docker-legacy: Mount: mysqldata: failed: error mounting directory"```

## Configuration Files

```yaml
rexray:
  logLevel:        debug
libstorage:
  logging:
    level:         debug
    httpRequests:  true
    httpResponses: true
  service: dobs
  server:
    services:
      dobs:
        driver: dobs
        dobs:
          token: 123456
          region: ams3
```

### Service Log
[rexray.log](https://github.com/rexray/rexray/files/3369895/rexray.log)
