### ISSUE TITLE
Segfault when try to launch in client server mode

### ISSUE THREAD

**Issue by tantra35** [rexray/rexray#1323]
# Summary
we use version 0.11.4

When we try to use rexray in client server mode we got Segfault on client side with folow stack trace:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x194490b]

goroutine 331 [running]:
github.com/rexray/rexray/agent/csi/libstorage.(*driver).Serve(0xc420294600, 0x336c200, 0xc420406180, 0x7f6fd42a9840, 0xc420154720, 0xc420151d00, 0x336c200)
        /go/src/github.com/rexray/rexray/agent/csi/libstorage/csi_service_libstorage.go:107 +0x4cb
github.com/rexray/rexray/agent/csi.(*csiService).Serve(0xc4204be4b0, 0x336c200, 0xc420406180, 0x0, 0x0, 0xc420151de0, 0x98)
        /go/src/github.com/rexray/rexray/agent/csi/mod_csi_service.go:72 +0x65
github.com/rexray/rexray/agent/csi.(*mod).Start.func2.1(0xc420074140, 0x33754a0, 0xc420406180)
        /go/src/github.com/rexray/rexray/agent/csi/mod_csi.go:247 +0x8a
created by github.com/rexray/rexray/agent/csi.(*mod).Start.func2
        /go/src/github.com/rexray/rexray/agent/csi/mod_csi.go:246 +0x57
```

Our server config is:

```
rexray:
  modules:
    default-csi:
      disabled: true

libstorage:
  tls:
    disabled: true
  host: tcp://127.0.0.1:7979
  embedded: true
  client:
    type: controller
  server:
    endpoints:
      public:
        address: tcp://:7979
    services:
      ebs:
        driver: ebs
      efs:
        driver: efs

ebs:
  region: us-east

efs:
  region: us-east
```

And our clieunt config is 

```
rexray:
  modules:
    default-csi:
      type: docker
      libstorage:
        service: ebs

    docker-ebs:
      type: docker
      desc: The efs docker module.
      host: unix:///run/docker/plugins/rexray-ebs.sock
      libstorage:
        service: ebs

    docker-efs:
      type: docker
      desc: The efs docker module.
      host: unix:///run/docker/plugins/rexray-efs.sock
      libstorage:
        service: efs

libstorage:
  host: tcp://rexray server addr:7979

  integration:
    volume:
      operations:
        mount:
          preempt: true
          rootPath: /
        create:
          disable: true
        remove:
          disable: true
```
