### ISSUE TITLE
[rexray/rbd]volume create error

### ISSUE THREAD

**Issue by kervin521** [rexray/rexray#1325]
# Summary
```
root@dbs-server10:/etc/ceph# docker volume create --driver=rexray/rbd:latest --name=test --opt=size=2
Error response from daemon: create test: VolumeDriver.Create: docker-legacy: Create: test: failed:

```

# New Feature

# Bug Reports

## Version
Please paste the output of `rexray version`. For example:

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.4
OsArch: Linux-x86_64
Commit: e7414eaa971b27977d2283f2882825393493179d
Formed: Tue, 15 Jan 2019 16:03:57 UTC
```
```shell
root@dbs-server10:/etc/ceph# docker plugin ls
ID                  NAME                                  DESCRIPTION            ENABLED
02155685d1bb        172.21.32.31:5000/rexray/rbd:latest   REX-Ray for Ceph RBD   true
2c3490d7f957        rexray/rbd:latest                     REX-Ray for Ceph RBD   true

```
## Actual Behavior
```shell
dbs-server10 rexray[97600]: time="2019-07-30T11:18:08Z" level=error msg="docker-legacy: List: failed: " host="unix:///var/run/rexray/711192545.sock" integrationDriver=linux osDriver=linux service=rbd storageDriver=libstorage time=1564485488253
```

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1. The first step should always be enabling `debug` logging.
  * Open the file `/etc/rexray/config.yml`
  * Set the log level for both REX-Ray and libStorage to `debug` and enable
HTTP request and response tracing for libStorage:
```yaml
rexray:
   logLevel: info
libstorage:
   logging:
      level: info
      httpRequests: true
      httpResponses: true
   service: rbd
   server:
      services:
         rbd:
            driver: rbd
            rbd:
               defaultPool: rbd
               testModule: true
               cephArgs: --id admin
               volumePath: /opt/ceph/rbd
```

## Configuration Files
Please paste any related configuration files, such as `/etc/rexray/config.yml`
in this section. Please use the appropriate formatting when pasting YAML.
content. For example:

```yaml
rexray:
   logLevel: info
libstorage:
   logging:
      level: info
      httpRequests: true
      httpResponses: true
   service: rbd
   server:
      services:
         rbd:
            driver: rbd
            rbd:
               defaultPool: rbd
               testModule: true
               cephArgs: --id admin
               volumePath: /opt/ceph/rbd
```

Proper formatting of pasted content is very important as structured data can
sometimes be accidentally recorded incorrectly, affecting the desired outcome.

## Logs
It is very important when filing an issue to include associated logs. There are
two different logs about which to be concerned: the service log (if REX-Ray is
running as a service) and the client log.

### Service Log
The REX-Ray service log file is stored at `/var/log/rexray/rexray.log`. Instead
of pasting the entire log file into this issue, please create a new
[gist](https://gist.github.com/) and paste the log file's contents there.
Please name the file `rexray-service.log` in the gist. The proper extension will
indicate how to format the contents.

### Client Log
The REX-Ray client will emit all of its logs to the console when operating with
debug logging enabled. Simply copy the contents of the console and paste them
into the same gist as above naming the file `rexray-client.log.sh`. The `sh`
extension will cause the contents to be formatted as if they were emitted
to the shell, which they were.
