### ISSUE TITLE
'nonempty' mount option does not work

### ISSUE THREAD

**Issue by Spicyq** [rexray/rexray#1347]
# Summary
Hello
I'm trying to use rexray s3fs driver for my docker swarm service but facing some troubles using 'nonempty' option. I've googled many threads using this option the same way, but can't make this work for me. Please help me to understand how to use it properly.
Thanks in advance.

# Bug Reports

## Version
```shell
$ lsb_release -d
Description:    Ubuntu 18.04 LTS
```
```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.4
OsArch: Linux-x86_64
Commit: e7414eaa971b27977d2283f2882825393493179d
Formed: Tue, 15 Jan 2019 19:03:57 MSK
```

## Expected Behavior
rexray mounts s3fs non-empty bucket

## Actual Behavior
Bucket is not empty. if you are sure this is safe, can use the 'nonempty' mount option.

## Steps To Reproduce
1. Start minio S3 server:
```
docker run -d --restart=always -p 9000:9000 -e "MINIO_ACCESS_KEY=myaccesskey" -e "MINIO_SECRET_KEY=mysecretkey" -v /var/data/s3/data:/data -v /var/data/s3/config:/root/.minio minio/minio:RELEASE.2020-06-03T22-13-49Z server /data
```
2. Install s3fs (1.82-1), rexray (0.11.4-1)
3. Create docker stack on swarm node with service using s3fs volume
4. When container started with successfully created new bucket (container must write something in new bucket), force remove container
5. Watch another container instance not starting, because bucket is not empty

## Configuration Files
`/etc/rexray/config.yml`:
```yaml
rexray:
  logLevel: debug
libstorage:
  logging:
    level:         debug
    httpRequests:  true
    httpResponses: true
    stdout: '/var/log/rexray/rexray.log'
  service: s3fs
  server:
    services:
      s3fs:
        driver: s3fs
        s3fs:
          endpoint: http://minio-server:9000
          accessKey: myaccesskey
          secretKey: mysecretkey
          options:
            - nonempty
            - uri=http://minio-server:9000
            - use_path_request_style
```
`/etc/docker/stack.yml`:
```
version: '3.7'
volumes:
  portainer.bucket:
    name: portainer.bucket
    driver: rexray
services:
  portainer:
    image: portainer/portainer:1.23.2
    command: "-H tcp://tasks.agent:9001 --tlsskipverify"
    volumes:
    - portainer.bucket:/data
```

### Service Log
[rexray-service.log](https://gist.github.com/Spicyq/ee5d827361446741234b5082851c492b) and 

### Syslog
```
Jun  5 20:54:01 master04 s3fs[3386889]: s3fs: MOUNTPOINT directory /var/lib/rexray/volumes/portainer.bucket is not empty. if you are sure this is safe, can use the 'nonempty' mount option.
Jun  5 20:54:01 master04 rexray[3378221]: time="2020-06-05T20:54:01+03:00" level=error msg="docker-legacy: Mount: portainer.bucket: failed: error mounting s3fs bucket" host="unix:///var/run/rexray/378211813.sock" integrationDriver=linux osDriver=linux service=s3fs storageDriver=libstorage time=1591379641990
Jun  5 20:54:02 master04 dockerd[1315]: time="2020-06-05T20:54:02.444687026+03:00" level=error msg="fatal task error" error="starting container failed: error while mounting volume '': VolumeDriver.Mount: docker-legacy: Mount: portainer.bucket: failed: error mounting s3fs bucket" module=node/agent/taskmanager node.id=nj611i50738hph6q0ak3wz4kv service.id=ttg2k8dejru02u1gzuxdmwmhl task.id=loznnevmfwpqhwx9bmpx0yrq
```

**Comment by Enquier** [comment]
I have found through a lot of testing that the "options" field only seems to work if you put it at the root of your config file like this:

```
rexray:
  logLevel: debug
libstorage:
  logging:
    level:         debug
    httpRequests:  true
    httpResponses: true
    stdout: '/var/log/rexray/rexray.log'
  server:
    services:
      s3fs:
        driver: s3fs
s3fs:
  accessKey: ****
  secretKey: ****
  endpoint: http://****
  options:
  - url=http://****
  - use_path_request_style
  - allow_other
  - nonempty
```

Also you either need:
`service: s3fs`

or 

```
  server:
    services:
      s3fs:
        driver: s3fs
```

you only need to use the second form if you are including multiple services

**Comment by Spicyq** [comment]
Yep, that works! Thank you so much for the help!
Another thing I forgot to mention is `/etc/passwd-s3fs` file (s3fs doesn't work without it):
```
<Your_accessKey>:<Your_secretKey>
```
And it seems like rexray s3fs doesn't have `uri` option, so here's my config that works, in case someone needs it: 
`/etc/rexray/config.yml`
```
libstorage:
  service: s3fs

s3fs:
  endpoint: http://minio-server:9000
  accessKey: myaccesskey
  secretKey: mysecretkey
  options: 'use_path_request_style,nonempty'
```
